{{- $releaseName := .Release.Name -}}
{{- $chartName := include "retiler.name" . -}}
{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $releaseName }}-{{ $chartName }}-secret
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "retiler.environment" . }}
    release: {{ $releaseName }}
    {{- include "retiler.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.dbConfig.username | b64enc }}
  DB_PASSWORD: {{ .Values.dbConfig.password | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.env.tilesStorage.s3ClientConfig.accessKey | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.tilesStorage.s3ClientConfig.secretKey | b64enc }}
{{- end }}