{
 "title": "retiler - instance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "projectName",
    "label": "project name",
    "query": {
     "query": "label_values(retiler_current_running_job_count,project)"
    }
   },
   { "name": "interval", "query": "1m,10m,30m,1h,6h,12h,1d" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(retiler_current_running_job_count,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total completed since restart",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "retiler_tiles_count{job=\"$instance\",status=\"completed\"}",
     "legendFormat": "Z{{z}}"
    }
   ]
  },
  {
   "title": "Total failed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "retiler_tiles_count{status=\"failed\", job=\"$instance\"}",
     "legendFormat": "Z{{z}}"
    }
   ]
  },
  {
   "title": "Running jobs",
   "type": "stat",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "retiler_current_running_job_count{project=\"$projectName\", job=\"$instance\"}",
     "legendFormat": "running jobs"
    }
   ]
  },
  {
   "title": "tiles rendered in $interval window",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (increase(retiler_tiles_count{project=\"$projectName\", job=\"$instance\"}[$interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Tile splitting duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(retiler_action_duration_seconds_bucket{kind=\"split\", project=\"$projectName\", job=\"$instance\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(retiler_action_duration_seconds_bucket{kind=\"split\", job=\"$instance\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "rate(retiler_action_duration_seconds_sum{kind=\"split\", project=\"$projectName\", job=\"$instance\"}[$interval]) / rate(retiler_action_duration_seconds_count{kind=\"split\",project=\"$projectName\", job=\"$instance\"}[$interval])",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Tile fetch duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(retiler_action_duration_seconds_bucket{kind=\"fetch\",project=\"$projectName\", job=\"$instance\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(retiler_action_duration_seconds_bucket{kind=\"fetch\",project=\"$projectName\", job=\"$instance\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "sum(rate(retiler_action_duration_seconds_sum{kind=\"fetch\",project=\"$projectName\", job=\"$instance\"}[$interval])) / sum(rate(retiler_action_duration_seconds_count{kind=\"fetch\",project=\"$projectName\", job=\"$instance\"}[$interval]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Tiles store",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(retiler_action_duration_seconds_bucket{kind=\"store\", project=\"$projectName\", job=\"$instance\"}[$interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(retiler_action_duration_seconds_bucket{kind=\"store\", project=\"$projectName\", job=\"$instance\"}[$interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "rate(retiler_action_duration_seconds_sum{kind=\"store\", project=\"$projectName\", job=\"$instance\"}[$interval]) / rate(retiler_action_duration_seconds_count{kind=\"store\", project=\"$projectName\", job=\"$instance\"}[$interval])",
     "legendFormat": "avg"
    }
   ]
  },
  { "title": "System metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Process CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{project=\"$projectName\", job=\"$instance\"}[$interval]) * 100",
     "legendFormat": "User CPU - {{instance}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{project=\"$projectName\", job=\"$instance\"}[$interval]) * 100",
     "legendFormat": "Sys CPU - {{instance}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{project=\"$projectName\", job=\"$instance\"}",
     "legendFormat": "Process Memory - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{project=\"$projectName\", job=\"$instance\"}",
     "legendFormat": "Heap Total - {{instance}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{project=\"$projectName\", job=\"$instance\"}",
     "legendFormat": "Heap Used - {{instance}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{project=\"$projectName\", job=\"$instance\"}",
     "legendFormat": "External Memory - {{instance}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{project=\"$projectName\", job=\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}